### ISSUE TITLE
Design Wireframes 

### ISSUE THREAD

**Issue by DharaniMuli** [NehaNavgale/VipraHub#8]

**Comment by naveenamadepally13** [comment]
Craeted wire frames design for -

1.Model Dashboard for logged in user
    - user menu
    - Comments section
    -Model dashboard
2.Model dashboard for non registered user

![architecturte](https://user-images.githubusercontent.com/47007814/52973457-da6fc080-3383-11e9-9b67-881d6549b102.PNG)
![decsriptiontab](https://user-images.githubusercontent.com/47007814/52973459-da6fc080-3383-11e9-92f1-a5cf784f08e6.PNG)
![logged in user menu](https://user-images.githubusercontent.com/47007814/52973460-da6fc080-3383-11e9-9a95-853be3c4eb08.jpg)
![loggedinmodeldashboard](https://user-images.githubusercontent.com/47007814/52973461-da6fc080-3383-11e9-91e8-b0155a04806d.PNG)
![model dashboard without login](https://user-images.githubusercontent.com/47007814/52973462-da6fc080-3383-11e9-8fbd-a98c866b65a2.jpg)
